### ISSUE TITLE
How to limit number of item for fields in document extraction

### ISSUE THREAD

**Issue by hitsense** [eyurtsev/kor#139]
Hi @eyurtsev, is there a way to mention (or limit) the number of items that should be extracted for each field in the schema?
Something like below - 

```
class ShowOrMovie(BaseModel):
    name: str = Field(
        description="The name of the movie or tv show",
        limit=3 <------
)
```

Also, how can I explicitly instruct GPT for certain cases like - Not adding random gibberish text if nothing is found
Can we mention the instruction in `description` parameter above?

**Comment by eyurtsev** [comment]
Hello!

Try adding this as information into the `description` parameter.

Then look at the prompt that gets generated:

```python
print(chain.prompt.format_prompt("[user_input]").to_string())
```

You could try grabbing the generated prompt and putting it into open AI playground and seeing if there's any place where adding this information in the prompt helps the LLM to do the correct thing. If you find something that works better than the `description` let me know. 

You can also further customize the prompt in the following manner

```Python

from langchain.prompts import PromptTemplate

instruction_template = PromptTemplate(
    input_variables=["format_instructions", "type_description"],
    template=(
        "Write some stuff here n\n"
        "{type_description}\n\n"
        "{format_instructions}"
        "Suffix here\n"
    ),
)


chain = create_extraction_chain(llm, schema, instruction_template=instruction_template)

print(chain.prompt.format_prompt(text='hello').to_string())
```

**Comment by eyurtsev** [comment]
^ I am assuming that you're trying to guide the LLM to provide a better output rather than post-processing the result to limit the result to 3 items.

If it's the latter, then you can use pydantic functionality to post-process the result.

**Comment by hitsense** [comment]
I want to guide the LLM to avoid giving random text for fields where answer was not found
And for some fields, I would like to limit the number of items extracted

For the former case, I am also seeing LLM just picking the text from my given examples instead of input text, making the result wrong

**Comment by eyurtsev** [comment]
Yeah that makes a lot of sense. 

I *think* the existing building blocks in `kor`  allow inserting information anywhere in the prompt.

So I think it makes sense to see if any paraphrasing of the prompt or adding extra details could help improve the quality of extraction with the LLM that's used. 

If you discover that anything helps, and you think could be done more convenient with API modifications, please let me know!

**Comment by MichaelVerdegaal** [comment]
I've had good succes with changing the wording to '**up to x**' in the description (e.g. `description="Extract up to 5 of this resource"`). I've not seen it go over my specified limits yet, though of course due to the nature of LLM's it's no guarantee that you actually get the maximum items even if they are available in the text.

**Comment by eyurtsev** [comment]
I'll close the issue for now as resolved.
