### ISSUE TITLE
'BaseLanguageModel' ERROR

### ISSUE THREAD

**Issue by malinphy** [eyurtsev/kor#145]
If I try to run the following command 
```
from kor import create_extraction_chain
```
I am having 
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema' (/usr/local/lib/python3.10/dist-packages/langchain/schema.py)
![image](https://user-images.githubusercontent.com/55249305/235620319-e9ff42e4-1f9c-4bfb-87b4-304e0ccf8036.png)

Any idea how to fix it?

**Comment by malinphy** [comment]
UPDATE 
problem solved with langchain==0.0.149 version.

**Comment by eyurtsev** [comment]
Thanks for letting me know! Looks like a change in langchain, I'll fix up today so langchain version does not need to be pinned.
