### ISSUE TITLE
about the kor output attribute mismatch

### ISSUE THREAD

**Issue by Feya** [eyurtsev/kor#169]
Hi, I guided kor to output up to 8 attributes. The problem I encountered was the output attribute mismatch, the answer should have appeared in attribute 5 'gender' appeared in attribute 4 'age'. 

As I checked the prompt that kor formatted  using  `print(chain.prompt.format_prompt("[user_input]").to_string())`, I got the prompt talking about output as the following:

> Please output the extracted information strictly in the above order. Please use a | as the delimeter. 

And the input example appeared like:

> attribute1 | attribute2 | attribute3 | attribute4 | attribute5 | attribute6 | attribute7 | attribute8 
> input1 | input2| input3| input4 | input5| input6| input7| input8

And this I assume as the main reason why there would be an attribute mismatch because 1) Sometimes the answer for attribute 1 is null, and the answer should have gone to attribute2 went to attribute1. 2) the model sometimes output 9 answers with 8 delimeter " | " which indicates llm was confused by how many attributues(questions) it should answer. 

So my question is how can I modify the kor so that the output won't use a | as a delimeter and won't output things like

> att1 | att2 | att3
> in1| in2| in3 

Instead, the output should be a dict: {'att1':'in1','att2':'in2','att3':'in3'}. In this way there won't be an attribute mismatch. 

Or if you have other better ways please tell me as well. 

Thank you very much.

**Comment by eyurtsev** [comment]
Hi @Feya !

Check out the guidelines here to see if any of these will help to improve performance with the csv encoding: https://eyurtsev.github.io/kor/guidelines.html

CSV encoding generally works well if you have to extract several entities from a piece of text. 

If you want to use JSON encoding, set the encoder_or_encoder_class to "json" see:

https://eyurtsev.github.io/kor/generated/kor.html#kor.create_extraction_chain 

You can also create a custom encoder by sub-classing from: https://eyurtsev.github.io/kor/generated/kor.encoders.html?highlight=encoder#kor.encoders.Encoder

Hope this helps! 

Happy extractions!

**Comment by Feya** [comment]
Thank you very much @eyurtsev !
Parameter encoder_or_encoder_class='json' is the perfect solution. Now I can get the answer in a more organized manner.
