### ISSUE TITLE
Accessing the original LLM response

### ISSUE THREAD

**Issue by tomerzcod7** [eyurtsev/kor#170]
Hey Eugene, 

Thanks for the hard work. This library works very well for us.
We have a requirement to access some metadata from the original openai API response. (Not just the usage).

Is there currently a way to do this?

**Comment by eyurtsev** [comment]
Hi Tomer, 

Apologies for delayed response -- I'm a bit low on time this week.  I'll take a look more carefully next week, but I suspect there's a way to do this using a callback manager.  (Maybe there's something simpler as well.)

I haven't exposed the passing `callbacks` to the chain through API, but you could instantiate the chain yourself in the meantime:

https://github.com/eyurtsev/kor/blob/main/kor/extraction/api.py#L101

Lines 101 - 108, and add a custom call back manager 

Something of this sort if you're using a chat model

```python
from langchain.callbacks.base import BaseCallbackHandler
from langchain.chat_models import ChatOpenAI
from langchain.schema import HumanMessage

class Handler(BaseCallbackHandler):
    def __init__(self):
        self.responses = []
        
    def on_llm_end(self, response, **kwargs) -> None:
        self.responses.append(response)

handler = Handler()
chat = ChatOpenAI(max_tokens=25, callbacks=[handler])

chat([HumanMessage(content="hello")])

handler.responses
```

**Comment by eyurtsev** [comment]
@tomerzcod7 let me know if this worked for you all

**Comment by eyurtsev** [comment]
Going to mark this issue as closed for now. Feel free to re-open if the solution above did not work
