### ISSUE TITLE
Kor with long documents

### ISSUE THREAD

**Issue by MauroLondon** [eyurtsev/kor#176]
I really like Kor, it's very helpful, congratulations for taking the time to create such a fantastic solution....

How can I use Kor with an accounts payable document with many pages and tables that exceed the total token allowed by OpenAI? 

Can you use embeds? 

Could you post an example code of a pdf document with many invoices?

**Comment by eyurtsev** [comment]
Hi Mauro, 

check out: https://eyurtsev.github.io/kor/document_extraction.html

You need to use a text splitter to break the document into smaller chunks and then you will need to combine the results.

I'm out on vacation until August so limited keyboard time until then.

Eugene
