### ISSUE TITLE
Loading schema from file

### ISSUE THREAD

**Issue by BorisWilhelms** [eyurtsev/kor#177]
Hi,

is there any way to load a schema from a file? Tried serializing an existing schema to JSON, but loading (via Object.parse_raw) fails, because there is no type discriminator for the attributes.

Is there already another way to do that? If not, are you planning to implement this or would you accept a PR for this?

Thanks
Boris

**Comment by eyurtsev** [comment]
Hi Boris!

Thanks for checking out the library!

I'm on vacation until the start of August so will be delayed at responding.

One possibility is using kor with pydantic style schema rather than native kor schema and relying on the adapter to map from pydantic schema to kor schema (see validation section in docs). This gives control over serialization and also creates a validator at the same time.

Would this work for your use case?

**Comment by BorisWilhelms** [comment]
Hi Eugene,

thank you for the response while you are on vacation. 

I am not that familiar with python and pydantic, so maybe it might be possible to use it for out use case.

Our use case is that the schema will be defined in a different application and can be changed by the user. My understanding with pydantic is, that I need to define the schema/model in code?

Alternatively, with a little change to the `ExtractionSchemaNode` (https://github.com/BorisWilhelms/kor/commit/e0bfa37cff02c9fb30f7bbad6d220739116d752c) it is possible to load the schema from JSON. The change introduces that the type of the attribute must be defined via the property `$type` in JSON. Here an example JSON:

```json
{
    "id": "person",
    "description": "Information about a person",
    "many": false,
    "attributes": [
        {
            "$type": "Text",
            "id": "name",
            "description": "The name of the person",
            "many": false,
            "examples": []
        },
        {
            "$type": "Text",
            "id": "position",
            "description": "The position of the person",
            "many": false,
            "examples": []
        },
        {
            "$type": "Number",
            "id": "age",
            "description": "The age of the person",
            "many": false,
            "examples": []
        }
    ],
    "examples": []
}
```

IMHO this is not the "prettiest" solution, but it works. And as I said, I don't know if our use case can be implemented with pydantic directly, but I will do some more research.

**Comment by eyurtsev** [comment]
That works! Will welcome a PR :). If possible could you add relevant unit tests   to verify serialization works?

**Comment by BorisWilhelms** [comment]
Will check what I can do with my simple python skills and create a PR!

Have a nice vacation!

**Comment by eyurtsev** [comment]
Thank you merged

**Comment by eyurtsev** [comment]
released as version 0.11.0

**Comment by BorisWilhelms** [comment]
Hey Eugene,

I managed to make the schema serializable to JSON. Please check PR #184 if it fits for you!

**Comment by BorisWilhelms** [comment]
Since this is all merged the issue can be closed.
