### ISSUE TITLE
predict_and_parse deprecated

### ISSUE THREAD

**Issue by BorisWilhelms** [eyurtsev/kor#185]
Since langchain 0.0.205 the `predict_and_parse` methods on the chain are deprecated. The solution is to set an output parser on the Chain directly. Kor currently does not set the output parser. It also uses `apredict_and_parse` for document `extract_from_documents`. `predict_and_parse` is also used in several places in the documentation. 

As was as I see it is quite a trivial change in api.py, tests and documentation. 

Do you want to implement the change or are you willing to accept an PR for that?

**Comment by eyurtsev** [comment]
Very happy to accept a PR if you're willing to contribute one. I'm away from a computer until Thursday so won't be able to release it until then.

**Comment by BorisWilhelms** [comment]
I will check this out in the next couple of days and create a PR.

**Comment by eyurtsev** [comment]
Merged! Thanks! @BorisWilhelms
