### ISSUE TITLE
Pydantic v2 support

### ISSUE THREAD

**Issue by eyurtsev** [eyurtsev/kor#206]
* Need to make kor pydantic v1 and v2 compatible

**Comment by codenamics** [comment]
how is it going?

**Comment by ericlinsd** [comment]
@eyurtsev when do you anticipate support for pydantic v2?

**Comment by ericlinsd** [comment]
@eyurtsev Thank you!

**Comment by eyurtsev** [comment]
@ericlinsd np -- not ready yet, but almost there will probably release by end of week

**Comment by eyurtsev** [comment]
Merged on main

**Comment by eyurtsev** [comment]
https://github.com/eyurtsev/kor/pull/223

**Comment by eyurtsev** [comment]
Release on pypi under version 1.0.0 -- has good unit test coverage, but let me know if there are any unexpected issues

**Comment by surkova** [comment]
There's an outstanding warning about config extra, otherwise 1.0.0 works like a charm with 2.3.0 for all I see! thank you!
