### ISSUE TITLE
Access the final prompt

### ISSUE THREAD

**Issue by blacksmithop** [eyurtsev/kor#211]
According to my understanding
```python
chain.run(text=("some text input"))
```
constructs a prompt based on all the parameters defined in the `Object` which is then sent to OpenAI. Is there any way I can access that final prompt?

**Comment by eyurtsev** [comment]
Hi @blacksmithop see if this helps https://eyurtsev.github.io/kor/tutorial.html#the-prompt

**Comment by blacksmithop** [comment]
@eyurtsev it does. Thank you 😄!
