### ISSUE TITLE
Added more attributes in schema but encountered validation error

### ISSUE THREAD

**Issue by Feya** [eyurtsev/kor#225]
Error message：
validation error for Text
id
  `<built-in function id>` is not a valid identifier. Please only use lower cased a-z, _ or the digits 0-9 (type=value_error)

Defined schema as
```
schema = Object(
    id = "travel_destination",
    description = "A source or destination for travel",
    attributes = [
        Text(
            id="city_name",
            description="The name of a city.",
        ),
        Text(
           id='country'
           description='The country of the city.",
        )
    ],
    examples = [])
```
I got the above error message.

**Comment by eyurtsev** [comment]
Try upgrading to version 1 -- it should have the validation on id removed

**Comment by Feya** [comment]
Thank you for your reply. 
After kor has been updated to v1.0.0, another error occured "UserWarning: The predict_and_parse method is deprecated, instead pass an output parser directly to LLMChain" when I tried to use the demo code 
```
    chain = create_extraction_chain(llm,summary_schema,encoder_or_encoder_class='json')
    output = chain.predict_and_parse(text=summary)['data']
```
Could you please show me how to modify code to solve the issue? 
Thank you very much!

**Comment by Feya** [comment]
I've changed 
```
output = chain.predict_and_parse(text=text)['data']
```
to 
```output = chain.run(text=text)['data']``` 
and that works!

**Comment by Feya** [comment]
reference :  https://github.com/gkamradt/langchain-tutorials/blob/main/data_generation/Expert%20Structured%20Output%20(Using%20Kor).ipynb
