### ISSUE TITLE
Kor with LLama2 or Mistral

### ISSUE THREAD

**Issue by abaranovskis-redsamurai** [eyurtsev/kor#238]
Hello,

Great work, thanks.

Kor examples are based on OpenAI models. Did you try it with LLama2 or Mistral?

Thanks,
Andrej

**Comment by eyurtsev** [comment]
I haven't had time unfortuntately. I tried with both Claude and OpenAI. For open AI `text-davinci-003` seemed to significantly outperform chat gpt 3.5 (but I haven't done comparisons against the function based API). If you end up establishing any benchmarks please let me know -- I know a lot of users are curious!

**Comment by abaranovskis-redsamurai** [comment]
Sounds good, I plan to give it a try. Will let you know.
