### ISSUE TITLE
Possible alternate approach to compare 

### ISSUE THREAD

**Issue by allisonmorrell** [eyurtsev/kor#27]
I am very interested in this project and think it opens up a lot of possibilities. I wanted to mention an alternate and complementary approach I've taken to this problem for consideration. It involves generally shorter prompts and fairly good accuracy. 

At a high level, my approach has been to format the desired output and examples as a markdown table. I chunk the input into sections of one or more paragraphs, and give to the model one at a time with the same prompt (trade off here between speed and reliability, also whether all the needed info is contained in the same chunk of text. Depends on the use case.)

I then validate the output by checking if it contains a table with the correct number of columns and correct column headers. If not, I resend the prompt until the correct format is output. I save the resulting information into a list of dictionaries from the content inside the table headers and table columns then reconstitute it into whatever format I want to use it for.

I find it most convenient and reliable to pretend that the assistant actually provided the user example output. This can be repeated for as many examples as are provided.

It might be a bit more limited as far as data types that can be structured out of the output. I haven't tried this, but I bet you could get the model to include comma separated values within one field in a table.

Here's an example, specific to the OpenAI chat format. Note that the API allows submitting multiple messages from the same party in a row.

User:
You will assist with locating data from unstructured text input from the user. You will output the data in a table with the following column headers:
|Name|Age|

User:
Alice is 30 years old. Bob, Alice's brother is younger than her. Bob is 28 years old. 

Assistant:
|Name|Age|
|Alice|30|
|Bob|28|

User:
My grandmother came over today. She's 90 years old, and her name is Mary. I'm 30 years old, my name is Alice. Leigh is 29. We're all going to a birthday party for Brenda, who is 2 years older than Mary. My grandfather is quite old. He will also be at the birthday party. He is 80. There will be cake! My grandfather's name is Bob.

Assistant:
Thank you for the input. Here's the table with the extracted information:

|Name|Age|
|Mary|90|
|Alice|30|
|Leigh|29|
|Brenda|92|
|Bob|80|

Please note that I have inferred Brenda's age from the statement "Brenda, who is 2 years older than Mary."

I theorize that this format has a fairly high reliability given the enormous volume of data structured in tables contained on the text on which the model was trained.

I imagine a person could find a way to convert from a desired output data structure like the ones in your current documentation to a columnar format and back, should this approach prove more reliable when tested.

Just putting this out there as I'm very interested in libraries that will facilitate structured output from text! If this is tried, I'd be happy to contribute.

**Comment by eyurtsev** [comment]
Hi @allisonmorrell! :wave:  

The format that you are suggesting sounds like it'll be great for some application, especially with the huge improvement over the current encoding in terms of number of tokens needed.

It'll work for applications where flattened data is OK, and as you the model could probably handle comma separated values to represent an embedded list or maybe even JSON encoding for nested objects. 

I'm wondering have you ever tried including a description of the table and of each column to see if it helps?  

If you're interested in trying to make it work you could see if you can generate a visitor for an Object type that outputs a markdown table, and a corresponding parser that can parse out information.

I don't yet have CI set up or any tests or linters, but will start working on that next week.

**Comment by eyurtsev** [comment]
Here's the example generator visitor:  https://github.com/eyurtsev/kor/blob/main/kor/examples.py#L58

The code that collects the examples is mixed in with the code that generates an encoding right now (XML). I'll need to think of an easy way of decoupling the encoder out (since I also wanted to test out JSON encoding).

Here's the type description code: https://github.com/eyurtsev/kor/blob/main/kor/type_descriptors.py#L12

The linked description will probably work fine for a markdown table style collected code.

**Comment by allisonmorrell** [comment]
I will take a look! I have tried including descriptions of the table as well, it probably helps. For common tasks like age, name, it doesn't seem to matter. It seems that the model will infer fairly well from the combination of table header and example. I have been thinking about how to generalize the table approach, will take a look at that code more closely when I have a chance. 

This comes of my experiments with legal citations for building a research database, where I also give the model a list of the citations to find based on a regular expression search. That case works particularly well with feeding in paragraphs one at a time but that's very application specific. There might be other use cases for the regular expression approach. Feeding in the specific ones I want also allows me to validate the output as the model will sometimes expand beyond what is specifically asked. One other advantage of the markdown table output is that it's easy to distinguish the comments and explanations (almost impossible to avoid and also sometimes helps the accuracy of the output) from the desired output. 

One other thing OpenAI has commented on is that the model doesn't seem to put much weight on the system message so I have put most instructions in the user message. 

This is the example prompt - it seems to fairly reliably infer from the column header "Treatment" and example what I'm looking for. 

System: 
You are a legal citation analyzer.

User:
The user provides a list of legal citations, and a paragraph with that citation in it. You return a table of only those cases which are included in the citation list. The next input will be the user's input.

User:
Citation: 2022 BCCA 1
Text: in Jones v Smith, 2022 BCCA 1 at paras 1-2, the court found that unjust enrichment was not established.

Assistant: 
|Citation|Case Name|Pinpoint|Treatment|
|2022 BCCA 1|Smith v Jones|paras 1-2|unjust enrichment was not established|


Model output (consolidated all paragraphs together, I loop through the paragraphs and record the model output for each paragraph number). You can see in this case without me asking for it it has inferred that it should separate different information for the same record by semicolon. 

| Paragraph | Citation | Case Name  | Pinpoint  | Treatment                                                                                                                                                                                                                                                                                                                                             
| 35 | 2013 BCSC 1143  | Sahyoun v Ho  | paras 16-25; para. 17 | Object of the Rules is to secure the just, speedy, and inexpensive determination of every proceeding on its merits; summary of the fundamental objectives and requirements of proper pleadings; requirement for a proper articulation of the legal basis supporting the claim(s); illustrates the two foundational purposes of efficiency and fairness |
| 36 | 2016 BCSC 278  | Huang v Silvercorp Metals Inc. | para. 19  | test under R. 9-5(1) is whether it is "plain and obvious that the action is certain to fail because the pleading contains a radical defect" |
| 37 | 2017 BCCA 78 | Krist v British Columbia | para. 24 | explains the procedure for applications to strike based on sub-rules 9-5(1)(b) and (d) |                                                                                                                                                                                                                                                               
| 38 | 2021 BCSC 289  | Gaucher v. British Columbia Institute of Technology | Justice MacDonald dealt with an application to strike pleadings |

**Comment by eyurtsev** [comment]
Thanks for all the details. I'll try generalizing the code in a bit to handle this use case.

**Comment by eyurtsev** [comment]
Released version 0.4.0. This version uses CSV encoding by default. Embedded lists and objects aren't supported yet with CSV encoding. See the prompt here: https://eyurtsev.github.io/kor/objects.html#object-schema

For embedded lists/objects one needs to use JSON encoding. 

If you end up taking this for a spin let me know!

**Comment by eyurtsev** [comment]
Closing issue for now.
