### ISSUE TITLE
Output to other formats than JSON

### ISSUE THREAD

**Issue by oliverbj** [eyurtsev/kor#35]
Is there any way to output anything else than JSON? I was thinking YAML for example.

The reason for asking this is that JSON is quite expensive in terms of "token usage" with OpenAI - I was thinking of using the output of kor multiple times in a LLM pipeline.

**Comment by eyurtsev** [comment]
Currently, the prompt consists of some description with a the type description (TypeScript or BulletPoint Format) and the output examples (XML). The XML is quite verbose as it repeats token names twice (once when opening a tag and once when closing a tag). 

What part of the prompt are you thinking about in terms of generating JSON? The input/output examples or the object type description?

Also curious are you trying to do zero-shot or few-shot in your use case?

**Comment by eyurtsev** [comment]
Release 0.4.0 uses JSON as default (instead of XML), and supports CSV as well. For CSV format, you can't use embedded lists or objects yet.

**Comment by eyurtsev** [comment]
Closing issue for now -- encoding supports CSV format now which is more efficient on token usage
