### ISSUE TITLE
Add details on different node type and usage to the documentation

### ISSUE THREAD

**Issue by smwitkowski** [eyurtsev/kor#87]
> I couldn't find information for different node types in the documentation. Is this something I could add?

Yes, please do!

_Originally posted by @eyurtsev in https://github.com/eyurtsev/kor/issues/84#issuecomment-1481654756_

**Comment by eyurtsev** [comment]
Added documentation here -- https://eyurtsev.github.io/kor/api.html#schema 

Feel free to PR any improvements :)

Closing for now
